import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HomeService {

  constructor() { }

  items() {
    return [
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
      {
        title: {
          B: 'B',
          I: 'I',
          N: 'N',
          G: 'G',
          O: 'O',
        },
        row1: {
          column1: '6',
          column2: '28',
          column3: '44',
          column4: '56',
          column5: '68',
        },
        row2: {
          column1: '13',
          column2: '22',
          column3: '40',
          column4: '59',
          column5: '70',
        },
        row3: {
          column1: '7',
          column2: '26',
          column3: '../../../../assets/img/logos/dollar.svg',
          column4: '49',
          column5: '66',
        },
        row4: {
          column1: '3',
          column2: '24',
          column3: '45',
          column4: '50',
          column5: '73',
        },
        row5: {
          column1: '5',
          column2: '16',
          column3: '34',
          column4: '54',
          column5: '62',
        },
      },
    ];
  }
}
